language: r
cache: packages

os:
  - linux
  - osx

r_github_packages:
  - r-lib/pkgdown

after_success:
  - Rscript -e "covr::coveralls()"
  - test $TRAVIS_OS_NAME = "linux" && R CMD INSTALL . # Install the package to build vignettes
  - test $TRAVIS_OS_NAME = "linux" && Rscript -e "pkgdown::build_site(preview = FALSE)" # Run pkgdown to check for issues (actual build happens on docs.ropensci.org)
